english = {
    "analyzed": "Analyzed",
    "analyzing": "Analyzing",
    "add_link": "Add Link",
    "add_library": "Add to Library",
    "added_library": "Added to Library",
    "batch_add": "Batch Add",
    "batch_add_failed": "Batch Add Failed!",
    "cancel": "Cancel",
    "check_for_updates": "Check for Updates",
    "config_success": "The configuration file is successfully reloaded!",
    "confirm_delete": "Are you sure you want to delete?",
    "delete": "Delete",
    "delete_library": "Delete (Including Library)",
    "domain_name": "Domain Name",
    "download_updates": "Download Updates",
    "downloading": "Downloading",
    "enter_link": "Enter URL",
    "error": "Error",
    "existing_task": "Task already exists",
    "existing_task_check_updates": "The task already exists. Do you want to check for updates?",
    "failed_to_build_task": "Failed to build the task! Unsupported URL!",
    "failed_to_delete_task": "Failed to delete the task! Task in use.",
    "failed_to_read_archive": "Failed to read archive!",
    "finished": "Finished",
    "host": "Host",
    "interrupted": "interrupted",
    "last_update": "Last Updated",
    "library": "Library",
    "module": "Module",
    "move_to_bottom": "Move to Bottom",
    "move_to_top": "Move to Top",
    "no": "No",
    "no_new_library_updates": "No New Library Updates",
    "okay": "Okay",
    "open_folder": "Open Folder",
    "open_webpage": "Open Webpage",
    "parsing_error": "Parsing Error!",
    "pause": "Paused",
    "ready": "Ready",
	"ready_to_analyize": "Ready to Analyize",
    "reload_profile": "Reload Profile",
    "remove": "Remove",
    "remove_compeleted": "Remove Completed",
    "rename": "Rename",
    "reselect_chapters": "Reselect Chapters",
    "reverse": "Reverse",
    "reverse_tooltip": "After clicking on any item, Shift + click on another item will reverse the item in between",
    "status": "Status",
    "start_analysis": "Start Analysis",
    "start_download": "Start Download",
    "selection_set": "Selection Set",
    "stop_analysis": "Stop Analysis",
    "stop_download": "Stop Download",
    "stop_download_confirm": "Are you sure you want to stop downloading?",
    "supported_domains": "Supported Domains",
    "task": "Task",
    "task_list": "Task List",
	"update": "Update",
}

lang = english
